/**
 * KitePulse AI - Domain Type Definitions & Schemas
 *
 * This module defines the core TypeScript interfaces representing market quotes,
 * historical candlestick intervals, AI trade proposals, active positions,
 * and portfolio performance summaries across Paper and Live trading modes.
 */

/**
 * Top-of-book market quote for an underlying equity or index instrument.
 */
export interface Quote {
  /** Underlying instrument ticker (e.g. 'NIFTY 50', 'BANK NIFTY', 'RELIANCE') */
  symbol: string;
  /** Last Traded Price (LTP) in INR */
  ltp: number;
  /** Net price change relative to previous trading day's close */
  change: number;
  /** Percentage price change relative to previous close */
  change_pct: number;
  /** Minimum contract lot size defined by NSE exchange */
  lot_size: number;
  /** Closest At-The-Money (ATM) Call option derivative contract */
  call_option?: {
    symbol: string;
    ltp: number;
  };
  /** Closest At-The-Money (ATM) Put option derivative contract */
  put_option?: {
    symbol: string;
    ltp: number;
  };
  /** Timestamp string (HH:MM:SS) of the quote generation */
  timestamp: string;
  /** Whether Zerodha Kite Connect credentials are active for this quote */
  configured?: boolean;
}

/**
 * Historical OHLCV candlestick bar record enriched with technical indicators.
 */
export interface Candle {
  /** Bar timestamp string (YYYY-MM-DD HH:MM:SS or ISO format) */
  time: string;
  /** Opening price during the interval */
  open: number;
  /** Highest price traded during the interval */
  high: number;
  /** Lowest price traded during the interval */
  low: number;
  /** Closing price at the end of the interval */
  close: number;
  /** Total traded share/contract volume during the interval */
  volume: number;
  /** 9-period Exponential Moving Average */
  ema_9?: number;
  /** 21-period Exponential Moving Average */
  ema_21?: number;
  /** Volume Weighted Average Price benchmark */
  vwap?: number;
  /** 14-period Relative Strength Index oscillator (0 - 100) */
  rsi?: number;
}

/**
 * Human-in-the-Loop Trade Proposal generated by AI or Quantitative Strategy.
 * Strictly requires explicit user confirmation before order dispatch.
 */
export interface TradeProposal {
  /** Unique 8-character proposal identifier */
  proposal_id: string;
  /** Underlying market symbol (e.g. 'NIFTY 50') */
  symbol: string;
  /** Executable instrument tradingsymbol (e.g. 'NIFTY 24850 CE' or 'RELIANCE MIS') */
  instrument: string;
  /** Actionable trade setup classification */
  signal_type: "BUY_CALL" | "BUY_PUT" | "BUY_EQUITY" | "SHORT_EQUITY";
  /** Directional market bias */
  direction: "BULLISH" | "BEARISH";
  /** Number of contract lots (strictly capped at 1 for risk containment) */
  lot_size: number;
  /** Executable unit quantity */
  quantity: number;
  /** Target execution entry price in INR */
  entry_price: number;
  /** Dynamic stop-loss price calculated from ATR volatility */
  stop_loss: number;
  /** Primary take-profit target (minimum 1:1.8 risk-to-reward) */
  target_1: number;
  /** Secondary extended profit target */
  target_2: number;
  /** Calculated risk-to-reward ratio formatted string (e.g. '1:2.0') */
  risk_reward: string;
  /** Algorithmic conviction score (50% to 99%) */
  confidence: number;
  /** Synthesized audio script for spoken radar feedback */
  verbal_pitch: string;
  /** Institutional technical indicator rationale */
  technical_rationale: string;
  /** Lifecycle approval state */
  status: "PENDING_APPROVAL" | "APPROVED" | "REJECTED" | "CANCELLED";
  /** Proposal generation time string (HH:MM:SS) */
  created_at: string;
  /** Time window in seconds before proposal automatically expires */
  expires_in_seconds: number;
}

/**
 * Actively tracked intraday position with real-time mark-to-market accounting.
 */
export interface Position {
  /** Unique position identifier (e.g. 'POS-LIVE-123456') */
  position_id: string;
  /** Associated broker or simulated order ID */
  order_id: string;
  /** Underlying ticker symbol */
  symbol: string;
  /** Tradingsymbol of the held instrument */
  instrument: string;
  /** Trade setup type */
  signal_type: string;
  /** Number of units or lots open */
  quantity: number;
  /** Average fill execution price */
  buy_price: number;
  /** Latest traded price refreshed from live tick stream */
  current_ltp: number;
  /** Stop-loss threshold triggering auto-exit */
  stop_loss: number;
  /** Take-profit threshold triggering auto-exit */
  target_1: number;
  /** Extended take-profit threshold */
  target_2: number;
  /** Unrealized mark-to-market Profit & Loss in INR */
  unrealized_pnl: number;
  /** Percentage return on capital deployed */
  pnl_pct: number;
  /** Timestamp when the position was initialized */
  opened_at: string;
  /** Current state ('OPEN' or 'CLOSED') */
  status: "OPEN" | "CLOSED";
  /** Execution environment ('PAPER' sandbox vs 'LIVE' Zerodha Kite) */
  mode: "PAPER" | "LIVE";
}

/**
 * Immutable audit record representing an executed or submitted order.
 */
export interface OrderRecord {
  /** Order identifier assigned by broker or simulation engine */
  order_id: string;
  /** Tradingsymbol executed */
  instrument: string;
  /** Transaction classification ('BUY' or 'SELL') */
  type: "BUY" | "SELL";
  /** Executed quantity */
  quantity: number;
  /** Average executed fill price */
  price: number;
  /** Order status reported by broker or simulator */
  status: string;
  /** Execution environment ('PAPER' or 'LIVE') */
  mode: string;
  /** Timestamp string of order event */
  timestamp: string;
  /** Realized P&L if the order was a position closing trade */
  pnl?: number;
}

/**
 * Consolidated high-level capital, P&L, and broker connectivity summary.
 */
export interface PortfolioSummary {
  /** Active system execution mode */
  mode: "PAPER" | "LIVE";
  /** Current paper trading virtual balance (initial + realized + unrealized) */
  paper_balance: number;
  /** Base starting paper capital (default: ₹1,00,000) */
  initial_balance: number;
  /** Mark-to-market floating P&L across all open positions */
  unrealized_pnl: number;
  /** Closed trade net gain/loss across completed orders */
  realized_pnl: number;
  /** Cumulative total P&L */
  total_pnl: number;
  /** Count of currently open positions */
  open_positions_count: number;
  /** Count of historical completed order records */
  completed_orders_count: number;
  /** Whether Zerodha Kite Connect session is currently active and authenticated */
  kite_connected: boolean;
  /** Cached real-time Kite margins and balance if available */
  kite_balance?: KiteBalance | null;
}

/**
 * Zerodha Kite Account Margin Segment details.
 */
export interface KiteMarginSegment {
  /** Total net available margin */
  net: number;
  /** Available usable intraday cash balance */
  available_cash: number;
  /** Available margin for new positions */
  available_margin: number;
  /** Total funds currently utilised */
  utilised: number;
  /** Opening balance at beginning of trading day */
  opening_balance?: number;
}

/**
 * Real-time Zerodha Kite Account Margin and Balance summary.
 */
export interface KiteBalance {
  /** Whether Zerodha Kite is actively connected and authenticated */
  connected: boolean;
  /** Equity & F&O derivatives segment margins */
  equity?: KiteMarginSegment;
  /** Commodity segment margins */
  commodity?: {
    enabled: boolean;
    net: number;
    available_cash: number;
    utilised: number;
  };
  /** Timestamp when balance was retrieved from Kite */
  timestamp?: string;
  /** Error message if Kite connection/token failed */
  error?: string;
}

/**
 * Historical record joining trade suggestions with position outcomes.
 */
export interface HistoryItem {
  proposal_id: string;
  symbol: string;
  instrument: string;
  signal_type: string;
  direction: string;
  lot_size: number;
  entry_price: number;
  stop_loss: number;
  target_1: number;
  target_2: number;
  risk_reward: string;
  confidence: number;
  technical_rationale?: string;
  suggestion_status: string;
  suggested_at: string;
  position_id?: string;
  position_status?: string;
  buy_price?: number;
  current_ltp?: number;
  unrealized_pnl?: number;
  realized_pnl?: number;
  pnl_pct?: number;
  exit_price?: number;
  close_reason?: string;
  opened_at?: string;
  closed_at?: string;
  mode?: string;
  overall_status: "OPEN" | "CLOSED" | "APPROVED" | "REJECTED" | "PENDING";
}
